version: '3.7'

services:
  gmco-ticketing-be:
    image: trahganjil/gmco-ticketing-be:{DOCKER_TAG}
    restart: unless-stopped
    container_name: gmco_be
    env_file:
      - .env
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - gateway_ingress
    