version: '3.7'

services:
  db:
    image: 'postgres:15-alpine'
    container_name: gmcgo-db
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gmcgo-network

  cache:
    container_name: gmcgo-cache
    image: redis:7.0-bullseye
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD}
    networks:
      - gmcgo-network

  app:
    build:
      context: .
      dockerfile: ./app.Dockerfile
    hostname: app
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - gmcgo-network
    depends_on:
      - db

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.10.2'
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: [ "CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "9200:9200"
    volumes:
      -  ./.docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    volumes:
      - ./.docker/logstash/


networks:
  gmcgo-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
  esdata:
    driver: local