version: '3.7'

services:
  db:
    image: 'postgres:15-alpine'
    container_name: gmcgo-db
    restart: unless-stopped
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    networks:
      - gmcgo-network

  cache:
    container_name: gmcgo-cache
    image: redis:7.0-bullseye
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --requirepass ${REDIS_PASSWORD}
    networks:
      - gmcgo-network

networks:
  gmcgo-network:
    driver: bridge