// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/frchandra/ticketing-gmcgo/app"
	"github.com/frchandra/ticketing-gmcgo/app/controller"
	"github.com/frchandra/ticketing-gmcgo/app/middleware"
	"github.com/frchandra/ticketing-gmcgo/app/repository"
	"github.com/frchandra/ticketing-gmcgo/app/service"
	"github.com/frchandra/ticketing-gmcgo/app/util"
	"github.com/frchandra/ticketing-gmcgo/config"
	"github.com/frchandra/ticketing-gmcgo/database"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializeServer() *gin.Engine {
	appConfig := config.NewAppConfig()
	logger := app.NewLogger(appConfig)
	client := app.NewCache(appConfig, logger)
	tokenUtil := util.NewTokenUtil(client, appConfig)
	userMiddleware := middleware.NewUserMiddleware(tokenUtil, logger)
	db := app.NewDatabase(appConfig, logger)
	logUtil := util.NewLogUtil(logger)
	userRepository := repository.NewUserRepository(db, logUtil)
	userService := service.NewUserService(userRepository, tokenUtil)
	adminMiddleware := middleware.NewAdminMiddleware(tokenUtil, logger, appConfig, userService)
	gateMiddleware := middleware.NewGateMiddleware(appConfig)
	scanQrMiddleware := middleware.NewScanQrMiddleware(tokenUtil, logger, appConfig, userService)
	userController := controller.NewUserController(userService, tokenUtil, appConfig)
	emailUtil := util.NewEmailUtil(appConfig, logUtil)
	authController := controller.NewAuthController(userService, tokenUtil, logUtil, emailUtil, appConfig)
	transactionRepository := repository.NewTransactionRepository(db)
	transactionService := service.NewTransactionService(transactionRepository, appConfig)
	reservationService := service.NewReservationService(appConfig, transactionService)
	seatRepository := repository.NewSeatRepository(db, logUtil)
	seatService := service.NewSeatService(appConfig, seatRepository, transactionRepository)
	reservationController := controller.NewReservationController(appConfig, db, logUtil, reservationService, transactionService, seatService, userService, tokenUtil)
	snapUtil := util.NewSnapUtil(appConfig, logger)
	transactionController := controller.NewTransactionController(transactionService, userService, snapUtil, logUtil)
	minioClient := app.NewMinio(appConfig, logger)
	eTicketUtil := util.NewETicketUtil(appConfig, minioClient, logUtil)
	snapService := service.NewSnapService(transactionService, seatService, transactionRepository, snapUtil, emailUtil, eTicketUtil, logUtil)
	snapController := controller.NewSnapController(snapService, snapUtil, transactionService, logUtil)
	configController := controller.NewConfigController(appConfig, logUtil)
	seatController := controller.NewSeatController(seatService, transactionService, logUtil)
	engine := app.NewRouter(appConfig, userMiddleware, adminMiddleware, gateMiddleware, scanQrMiddleware, userController, authController, reservationController, transactionController, snapController, configController, seatController)
	return engine
}

func InitializeMigrator() *database.Migrator {
	appConfig := config.NewAppConfig()
	logger := app.NewLogger(appConfig)
	db := app.NewDatabase(appConfig, logger)
	migrator := database.NewMigrator(db)
	return migrator
}

func InitializeEmail() *util.EmailUtil {
	appConfig := config.NewAppConfig()
	logger := app.NewLogger(appConfig)
	logUtil := util.NewLogUtil(logger)
	emailUtil := util.NewEmailUtil(appConfig, logUtil)
	return emailUtil
}

// injector.go:

var MiddlewareSet = wire.NewSet(middleware.NewUserMiddleware, middleware.NewAdminMiddleware, middleware.NewGateMiddleware, middleware.NewScanQrMiddleware)

var UserSet = wire.NewSet(repository.NewUserRepository, service.NewUserService, controller.NewAuthController, controller.NewUserController)

var ReservationSet = wire.NewSet(service.NewReservationService, controller.NewReservationController)

var SeatSet = wire.NewSet(controller.NewSeatController, repository.NewSeatRepository, service.NewSeatService)

var TransactionSet = wire.NewSet(controller.NewTransactionController, repository.NewTransactionRepository, service.NewTransactionService)

var SnapSet = wire.NewSet(controller.NewSnapController, service.NewSnapService)

var GateSet = wire.NewSet(controller.NewConfigController)

var UtilSet = wire.NewSet(util.NewTokenUtil, util.NewSnapUtil, util.NewEmailUtil, util.NewETicketUtil, util.NewLogUtil)
