name: Docker Image CI

on: push

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag trahganjil/gmco-ticketing-be:$(git rev-parse --short HEAD)
    - name: Push to DockerHub
      run: docker login -u ${{ secrets.DH_USER }} -p ${{ secrets.DH_PASS }} && docker push trahganjil/gmco-ticketing-be:$(git rev-parse --short HEAD)
