name: Docker Image CI

on:
  push:
    branches:
    - master
    - development
    - fix/otp-window

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag trahganjil/gmco-ticketing-be:$(git rev-parse --short HEAD)
    - name: Push to DockerHub
      run: docker login -u ${{ secrets.DH_USER }} -p ${{ secrets.DH_PASS }} && docker push trahganjil/gmco-ticketing-be:$(git rev-parse --short HEAD)

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Run Docker Container
      run: export DOCKER_TAG=$(git rev-parse --short HEAD) && cp ~/projects/vault/.env .env && docker compose up -d
